"""End-to-end functional tests: run the `nonhuman-screen` CLI on real BAMs.

These drive the installed console script as a subprocess (a true CLI test)
against committed fixtures:

* the mini kraken2 database in ``tests/data/kraken2_mini_strep`` (a single
  synthetic *Streptococcus pyogenes* / taxid 1314 reference), and
* GIAB human BAMs in ``tests/data/bam`` — the **negative** controls — plus
  ``HG002_child.strep.bam``, the child BAM with 500 strep reads spliced in
  (the **positive** control).

Fixtures are generated by ``scripts/build_test_fixtures.py`` and committed, so
this only needs the ``kraken2`` binary (not ``kraken2-build``). Skipped when
kraken2 or the fixtures are absent.
"""

import json
import os
import shutil
import subprocess
import sys

import pytest

_DATA = os.path.join(os.path.dirname(__file__), "data")
_DB = os.path.join(_DATA, "kraken2_mini_strep")
_BAM = os.path.join(_DATA, "bam")

_KRAKEN2 = shutil.which("kraken2") is not None
_FIXTURES = os.path.isfile(os.path.join(_DB, "hash.k2d"))

# Prefer the installed console script (the real CLI); fall back to `python -m`
# so the test also runs from a bare virtualenv where PATH lacks the bin dir.
_CLI_CMD = (
    ["nonhuman-screen"] if shutil.which("nonhuman-screen")
    else [sys.executable, "-m", "nonhuman_screen.cli"]
)

pytestmark = pytest.mark.skipif(
    not (_KRAKEN2 and _FIXTURES),
    reason="requires the kraken2 binary and the committed mini-DB fixtures",
)

NEGATIVE_BAMS = ["HG002_child.bam", "HG003_father.bam", "HG004_mother.bam"]
POSITIVE_BAM = "HG002_child.strep.bam"


def _classify(bam_name, tmp_path):
    """Run `nonhuman-screen classify` on a BAM and return its summary dict."""
    prefix = str(tmp_path / "out")
    proc = subprocess.run(
        _CLI_CMD + [
            "classify",
            "--bam", os.path.join(_BAM, bam_name),
            "--kraken2-db", _DB,
            "--out-prefix", prefix,
        ],
        capture_output=True, text=True,
    )
    assert proc.returncode == 0, (
        f"CLI failed (rc={proc.returncode})\nSTDERR:\n{proc.stderr}"
    )
    with open(prefix + ".summary.json") as fh:
        return json.load(fh)


@pytest.mark.parametrize("bam", NEGATIVE_BAMS)
def test_negative_control_reports_no_nonhuman(bam, tmp_path):
    """Original human BAMs must show zero non-human content."""
    summary = _classify(bam, tmp_path)
    assert summary["taxonomy_available"] is True
    assert summary["reads"] > 0
    assert summary["classified"] == 0
    assert summary["nonhuman_fraction"] == 0.0
    assert summary["fractions"]["bacterial"] == 0.0


def test_positive_control_detects_injected_strep(tmp_path):
    """The strep-injected BAM must be flagged as non-human / bacterial."""
    summary = _classify(POSITIVE_BAM, tmp_path)
    assert summary["taxonomy_available"] is True
    # ~500 injected strep reads (pure Streptococcus sequence) all classify.
    assert summary["classified"] >= 400
    # Negatives are exactly 0.0, so any comfortable margin separates them.
    assert summary["nonhuman_fraction"] > 0.02
    assert summary["fractions"]["bacterial"] > 0.02
    # Injected reads are bacterial, not viral/fungal/etc.
    assert summary["fractions"]["bacterial"] == pytest.approx(
        summary["nonhuman_fraction"]
    )


def test_positive_exceeds_negative(tmp_path):
    """The positive control's non-human fraction must exceed every negative."""
    positive = _classify(POSITIVE_BAM, tmp_path)["nonhuman_fraction"]
    for bam in NEGATIVE_BAMS:
        assert positive > _classify(bam, tmp_path)["nonhuman_fraction"]
